### ISSUE TITLE
Android Kiwi Browser

### ISSUE THREAD

**Issue by FuckingToasters** [anaclumos/bing-chat-for-all-browsers#12]
Hello, I just got a mail that I were accepted to Bing Chat after sriund a week, I then tried to access it on desktop which didn't work even in edge browser, needed to use an VPN.

Now I wanted to use it in mobile and because the bing app don't work plus mobile edge don't has the chat feature yet I installed this extension using the kiwi browser. I then needed to switch to desktop mode to get rid of the waitlist popup. After doing so, it asked me to use edge meaning that the extiobs did not worked as it should

**Comment by anaclumos** [comment]
Thanks for reaching out about your difficulties accessing Bing Chat. I'm sorry to hear that you're still having trouble even when accessing it on your desktop. If you're encountering issues accessing the service on a desktop, there may be a regional lock or limit that may be out of this project's scope. Could you provide more context so that I can look into this problem?

If you're using Kiwi browser just for Bing Chat, try Firefox. Some users have reported success accessing Bing Chat on their mobile devices using [Firefox for mobile](https://addons.mozilla.org/en-US/firefox/addon/bing-chat-for-all-browsers/), so you could try that as an alternative if you haven't already

Let me know if there's anything else I can do to help.

**Comment by anaclumos** [comment]
Please feel free to reopen the issue if the issue persists.
