### ISSUE TITLE
Not working on Android Kiwi Browser 

### ISSUE THREAD

**Issue by Practicalbutterfly5** [anaclumos/bing-chat-for-all-browsers#26]
When I click the extension, and then click open bing chat, it simply redirects me to bing.com/chat and a pop-up appears saying "Chat mode is only available when you have access to the new Bing."

I can access the new bing chat from the bing app without any problem

**Comment by anaclumos** [comment]
Can you share the Android version and the Kiwi version? I cannot access Android and Kiwi, so it may be hard to debug. Feel free to let me know if there's anything else I can do to help. #12

**Comment by Practicalbutterfly5** [comment]
Kiwi Version: 107.0.5304.74
Extension version: 1.0.4
Android version: 11

**Comment by emengweb** [comment]
same here

**Comment by kvn1351** [comment]
Same

**Comment by Bejukoro** [comment]
same too

**Comment by nitincodery** [comment]
You don't need any extension to access bing chat. Simply, open developer tools from menu. Go to network conditions:

![IMG_20230315_080707_482](https://user-images.githubusercontent.com/54881266/225188266-46a00853-9f2a-4cb8-8c44-826881eb2f3b.jpg)

In network conditions, uncheck, Use browser default and select user agent as Microsoft Edge Android.

![IMG_20230315_081116_380](https://user-images.githubusercontent.com/54881266/225188791-73c39880-f4e0-40e9-b795-b884126bf382.jpg)

Now close developer tools tab, open bing chat in new tab and it will work, this same method works on computer as well, no need of any extension. For using in computer select user agent as edge chromium instead of android.

**Comment by emengweb** [comment]
Wow! It worked!!!

nitincodery ***@***.***> 于2023年3月15日周三 10:29写道：
