### ISSUE TITLE
[opera GX] Chat Mode is only available when you use the new Bing

### ISSUE THREAD

**Issue by CrimsonCuttle** [anaclumos/bing-chat-for-all-browsers#93]
After clearing cookies and logging in whilst using Opera GX (which works with Chrome addons) I am just led to a page that tells me to use Edge instead of taking me to the chat.

**Comment by anar4732** [comment]
same here. I think they need to add support for opera to make it work.

**Comment by anaclumos** [comment]
#2 We couldn't find a solution for Opera. Do any of you know the solution?

**Comment by Kenny1291** [comment]
By [default](https://dev.opera.com/extensions/content-scripts/), extensions on Opera are not allowed to access search results pages. I played around a bit trying to get Bing Chat working on Opera, but even after enabling the option to give access to extensions to search page results, I wasn’t able to do so because for some unknown reasons some of the initial requests still got sent with the Opera User-Agent.
